import turtle
t = turtle.Turtle()
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(180)
t.forward(100)
t.right(90)
t.forward(200)
t.left(90)
t.forward(100)
t.left(180)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(180)
t.forward(100)
t.right(90)
t.forward(200)
t.left(90)
t.forward(100)

t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
