import turtle
t = turtle.Turtle()
t.left(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(180)
t.forward(100)
t.right(90)
t.forward(200)
t.left(90)
t.forward(100)
t.left(180)
t.forward(100)
t.right(90)
t.forward(100)
t.right(90)
t.forward(100)
t.left(90)
t.forward(100)
t.left(180)
t.forward(100)
t.right(90)
t.forward(200)
t.left(90)
t.forward(100)

t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)
t.left(90)
t.forward(200)

t.forward(50)
t.left(90)
t.forward(200)
t.left(90)
t.forward(50)
t.left(180)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(300)
t.left(90)
t.forward(300)
t.left(90)
t.forward(300)
t.left(90)
t.forward(300)
t.left(90)
t.forward(300)
t.left(45)
t.forward(240)
t.left(98)
t.forward(215)
t.left(37.1)
